### ISSUE TITLE
ex tool - unable to escape 'line feed' character for cards' skill descriptions in Rance10EX.ex

### ISSUE THREAD

**Issue by Nostaljaded** [nunuhara/alice-tools#12]
Hi,

`r` character is used as 'line feed' character for Rance X cards' skill descriptions in Rance10EX.ex.

* using `\r` outputs an empty space;
* using `full-width r` has spacing issues

![1](https://user-images.githubusercontent.com/28423237/102155613-e75b7f00-3e49-11eb-8fa5-92548f2f26a3.png)

Here's the test line:
`	{ 1008, "ランスアタック", 1, 3, "", 3, 100, 1, 300, 7, 0, 0, 0, "", 1, 0, "Melee(3x)r　pq\rstr　pqｒst" },`

**Is it fixable or is there a workaround?**

_Using alice-tools 0.8.0 on Win7._

**Comment by nunuhara** [comment]
Yes, I actually helped someone with this exact issue via email just recently. I'll copy and paste my reply here:

>As for the newline issue, the function SkillDescriptionView@0 contains the code:
>
>    S_PUSH "r"
>    S_PUSH "\n"
>    CALLHLL String Replace -1
>
>If you changed the "r" to something else (like "|" for example) and then updated all of the skill descriptions >to use "|" instead of "r" I think you should then be able to use "r" normally in the descriptions.

(Note: apparently the function PlayerDetailSkillView@SetParam also needs to be changed in a similar way.)

In other words, you need to dump the code (`alice ain dump -c ...`), edit the code in the `SkillDescriptionView@0` and `PlayerDetailSkillView@SetParam` functions as described above, then rebuild the .ain file (`alice ain edit -c ...`). Finally, you would have to edit the descriptions in the .ex file to use "|" instead of "r".

**Comment by Nostaljaded** [comment]
Tried but doesn't work on my end.

Could you do a quick test to see if it works?

**Comment by Nostaljaded** [comment]
Found the relevant `S_PUSH "r"` in `CardConstructProcessCacheBackSkill@Create`

Thanks. :)
