### ISSUE TITLE
Folder Dumping/Batch Dumping

### ISSUE THREAD

**Issue by Eraea** [nunuhara/alice-tools#16]
Is batch dumping possible? If not then is it possible to have batch dumping?
I have been working on .pactex files (oddly enough seem to be just .ex files) extracted from a <gamename>Pact.afa file and it contains alot of them so it's been hard on my fingers typing alice ex dump per file.

**Comment by nunuhara** [comment]
It's not possible currently, but it's something I've been thinking about adding for a while now.
I think the way I'll do it is to have the `alice ar extract` command automatically dump .ex/.pactex files, similar to how it converts image formats.

**Comment by nunuhara** [comment]
This isn't quite fixed as suggested, but there is a much better workflow for dealing with pact archives now. This is due to three changes:

1. Proper support for .afa v3 archives in `alice ar extract`
2. Automatic dumping of .ex/.pactex files by `alice ar extract`
3. Batch conversion of .x files to .ex/.pactex by `alice ar pack`

For example, to edit the pact archive in Dohna Dohna, you could do the following,

Extract/dump the pact archive:

    alice ar extract -o x dohnadohnaPact.afa

Create a BATCHPACK manifest (we'll call it dohnadohnaPact.manifest):

    #BATCHPACK
    dohnadohnaPact.afa
    x,x,pactex,pactex

Rebuild the pact archive:

    alice ar pack dohnadohnaPact.manifest

**Comment by Eraea** [comment]
I think this helps much better than the previous labor of copy pasting and editing, so I very much appreciate the new feature!

**Comment by SUNCRIS** [comment]
Hi i have been been trying to modify the dohnadohnaPact.afa file, had no problems extracting but when i try to pack them back with the manifest that is posted:

#BATCHPACK
dohnadohnaPact.afa
x,x,pactex,pactex

This error appears:  _ERROR: line 2: "pactex" is not a directory_

I have the x folder and the manifest file in same folder.

I tried writing other manifests and the ones that worked without errors make the dohnadohnaPact.afa file have 10 times the original size and dont work ingame...
