### ISSUE TITLE
Oyako Rankan .ain custom line breaks

### ISSUE THREAD

**Issue by ThisPyro** [nunuhara/alice-tools#7]
I was able to dump and edit the .ain file but I cant figure out how to make new line breaks.
The original line breaks are new strings with their own id but I know it's possible to make new one because there is a translation of the intro which has custom line breaks. 
Sadly I get errors when I try to dump his version and cant look how he did it.

**Comment by nunuhara** [comment]
You _should_ be able to add new line breaks by adding "\n" to the message you want to break. E.g.

    m[123] = "first line\nsecond line"

The other way to add line breaks would be to edit the code, which is a bit tricky with these tools. E.g. if the original code was,

    MSG 0x123 ; "orignal japanese message"
    CALLFUNC A

You could change this to,

    .SETMSG 0x123 "first line" ; modify the original message
    CALLFUNC R                 ; add line break
    .MSG "second line"         ; add a new message
    CALLFUNC A                 ; wait for user input

Editing the code like this is the "correct" way of adding line breaks but I've found the "\n" method works too.

In general if you need to edit the code I would recommend using the "AinDecompiler" program linked [here](https://alicesoft.fandom.com/wiki/User_blog:RottenBlock/System_Programming_Resources) rather than alice-tools, as it's much more convenient. I think it should work with Oyako Rankan, but it doesn't work on newer titles.

**Comment by ThisPyro** [comment]
I already tried the first one but it did not work.
`m[1974] = "test\nbreak"`
![Unbenannt](https://user-images.githubusercontent.com/59779851/100112143-2ad85400-2e6f-11eb-8c18-1b98aa15ff79.PNG)
I'll check out AinDecompiler and thanks for the help.

**Comment by ThisPyro** [comment]
I figured out how to do it the "correct" way with AinDecompiler, again thanks.
